### ISSUE TITLE
[bounty] Further content transfer into newsroom (existing article translations)

### ISSUE THREAD

**Issue by ftrader** [bitcoin-cash-node/bchnode-web#110]
Thanks to @ChaituVR for doing a search on missing content in our site newsroom.

The translations listed below should be imported, and bounties on them are put out as below.

Content should be correctly titled and dated, and include all the significant content including any article body images and references to other content. Footer links to contact resources and wordmark logos of BCHN project resources can be omitted. Other hyperlinks should be in working order.

Each imported article should be a separate PR (to facilitate review).

Bounty amounts will be paid out in BCH at the USD/BCH conversion rate at the time.
Bounty amounts in USD are listed next to each article. Only one bounty will be paid per completed (reviewed & accepted) article PR.

For Article Announcing Bitcoin Cash Node
- [X] Japanese - https://read.cash/@emergent_reasons/bitcoin-cash-node-909e5894 - ~~bounty : 50 USD~~ , completed by @ChaituVR in #108
- [X] Korean - https://read.cash/@sittufeing/bitcoin-cash-node-korean-79c26825 - ~~bounty : 50 USD~~ , completed by @merc1er in #111 
- [X] Portuguese. - https://read.cash/@phabulu/bitcoin-cash-node-portuguese-00bee10a - ~~bounty : 50 USD~~ , completed by @ChaituVR in #115  

For Article Bitcoin Cash Node Community Survey - March 2020
- [X] Portuguese - https://read.cash/@phabulu/pesquisa-da-comunidade-bitcoin-cash-node-marco-de-2020-c3a8b7ee - ~~bounty : 50 USD~~ , completed by @ChaituVR in #107

For Bitcoin Cash Node 2020
- [x] Portuguese - https://read.cash/@phabulu/bitcoin-cash-node-2020-planos-para-atualizacao-de-maio-e-adiante-4b16ada8 - bounty : 50 USD , completed by @ChaituVR in #112  
- [X] Spanish (partial) - https://read.cash/@DarthRoison/bch-node-nuestro-plan-de-trabajo-de-cara-a-la-actualizacion-de-mayo-a1569797 - ~~bounty : 50 USD~~ , completed by @ChaituVR in #114 / #124

For BCHN announcement regarding Bitcoin Cash (BCH) upgrade specifications -
- [X] Portuguese - https://read.cash/@phabulu/anuncio-do-bchn-sobre-as-especificacoes-de-atualizacao-do-bitcoin-cash-bch-portugues-1d11944b - ~~bounty : 50 USD~~ completed by @ChaituVR in #109

As bounties are completed, the relevant PRs will be added to the information above and marked as completed.

**Comment by ftrader** [comment]
Pending review: #107 , #108 , #109 by @ChaituVR

**Comment by ftrader** [comment]
Closing as all bounties have been completed.
